//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizIntegrator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIEndpoint
    {
        public System.Guid Id { get; set; }
        public System.Guid API_Id { get; set; }
        public string EndPoint { get; set; }
        public string TransactionType { get; set; }
        public string HttpVerb { get; set; }
        public string Name { get; set; }
    }
}
