//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizIntegrator.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BizIntegratorEntities : DbContext
    {
        public BizIntegratorEntities()
            : base("name=BizIntegratorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APIEndpoint> APIEndpoints { get; set; }
        public virtual DbSet<API> APIs { get; set; }
        public virtual DbSet<ConfirmedOrder> ConfirmedOrders { get; set; }
        public virtual DbSet<ConfirmOrderRequest> ConfirmOrderRequests { get; set; }
        public virtual DbSet<DocumentHeader> DocumentHeaders { get; set; }
        public virtual DbSet<DocumentIdentification> DocumentIdentifications { get; set; }
        public virtual DbSet<InvoiceLine> InvoiceLines { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<LoggedInUser> LoggedInUsers { get; set; }
        public virtual DbSet<LoginRequest> LoginRequests { get; set; }
        public virtual DbSet<LoginRespons> LoginResponses { get; set; }
        public virtual DbSet<OrderLine> OrderLines { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<ProblemDetail> ProblemDetails { get; set; }
        public virtual DbSet<Receiver> Receivers { get; set; }
        public virtual DbSet<Sender> Senders { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupplierVendor> SupplierVendors { get; set; }
        public virtual DbSet<UploadedInvoice> UploadedInvoices { get; set; }
    }
}
