//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizIntegrator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.UploadedInvoices = new HashSet<UploadedInvoice>();
        }
    
        public System.Guid Id { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceType { get; set; }
        public string RefInvoiceNumber { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> InvoiceAmountInc { get; set; }
        public Nullable<int> NumberOfLines { get; set; }
        public Nullable<decimal> TotalQuantity { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public Nullable<decimal> AcPercentage { get; set; }
        public string CgrnNumber { get; set; }
        public string COrderNumber { get; set; }
        public Nullable<System.Guid> OrderLine_Id { get; set; }
        public Nullable<System.Guid> Order_Id { get; set; }
        public Nullable<System.Guid> InvoiceLine_Id { get; set; }
    
        public virtual InvoiceLine InvoiceLine { get; set; }
        public virtual OrderLine OrderLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadedInvoice> UploadedInvoices { get; set; }
        public virtual Order Order { get; set; }
    }
}
