//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizIntegrator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoggedInUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoggedInUser()
        {
            this.LoginRequests = new HashSet<LoginRequest>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> User_Id { get; set; }
        public string Username { get; set; }
        public string Initials { get; set; }
        public string Surname { get; set; }
        public string CompanyNo { get; set; }
        public string CompanyName { get; set; }
        public string EMail { get; set; }
        public System.Guid Permission_Id { get; set; }
        public Nullable<System.Guid> Vendor_Id { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual SupplierVendor SupplierVendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginRequest> LoginRequests { get; set; }
    }
}
