//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizIntegrator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderLine()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> OrdLn { get; set; }
        public string ItemNo { get; set; }
        public string ItemDesc { get; set; }
        public string MfrItem { get; set; }
        public Nullable<decimal> QtyConv { get; set; }
        public Nullable<decimal> OrdQty { get; set; }
        public string PurcUom { get; set; }
        public Nullable<decimal> PurcUomConv { get; set; }
        public string TaxCde { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> UnitPrc { get; set; }
        public Nullable<decimal> LineTotExcl { get; set; }
        public Nullable<decimal> LineTotTax { get; set; }
        public Nullable<decimal> LineTotVal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
