//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizIntegrator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemDetail
    {
        public System.Guid Id { get; set; }
        public string Type { get; set; }
        public string Title { get; set; }
        public Nullable<int> Status { get; set; }
        public string Detail { get; set; }
        public string Instance { get; set; }
        public Nullable<System.Guid> Supplier_Id { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
