//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizIntegrator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadedInvoice
    {
        public System.Guid Id { get; set; }
        public string InvNo { get; set; }
        public string OrdNo { get; set; }
        public string VendorNo { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Status { get; set; }
        public string Message { get; set; }
        public string Uploaded { get; set; }
        public Nullable<System.Guid> Invoice_Id { get; set; }
        public Nullable<System.Guid> Order_Id { get; set; }
        public Nullable<System.Guid> Vendor_Id { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Order Order { get; set; }
        public virtual SupplierVendor SupplierVendor { get; set; }
    }
}
